default_language_version:
  python: python3
# Skip the pre-commit check for below directories to have
# a consistency with the official tfrecord preprocessing scripts
exclude: "^(streaming/text/convert/enwiki/)"
repos:
- repo: git@github.com:astral-sh/ruff-pre-commit.git
  # Ruff version.
  rev: v0.2.2
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
- repo: git@github.com:google/yapf.git
  rev: v0.32.0
  hooks:
  - id: yapf
    name: yapf
    description: "A formatter for Python files."
    entry: yapf
    args: [-i, -vv, -p]  # inplace
    language: python
    types: [python]
    additional_dependencies:
    - "toml"
- repo: git@github.com:pycqa/isort.git
  hooks:
  - id: isort
  rev: 5.12.0
- repo: git@github.com:pre-commit/pre-commit-hooks.git
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-builtin-literals
    args:
    - --no-allow-dict-kwargs
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-shebang-scripts-are-executable
  - id: pretty-format-json
    args:
    - --autofix
    - --no-sort-keys
    - --indent=4
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: git@github.com:Lucas-C/pre-commit-hooks.git
  rev: v1.5.4
  hooks:
  - id: insert-license
    args:
    - --license-filepath
    - .pre-commit/FILE_HEADER
    - --comment-style
    - "#"
    - --allow-past-years
    types: [python]
- repo: git@github.com:myint/docformatter.git
  rev: v1.5.0
  hooks:
  - id: docformatter
    args: [--in-place, --wrap-summaries=99, --wrap-descriptions=99]
    exclude: "(tests)"
- repo: git@github.com:adrienverge/yamllint.git
  rev: v1.28.0
  hooks:
  - id: yamllint
    name: yamllint
    description: This hook runs yamllint.
    entry: yamllint
    language: python
    types: [file, yaml]
